### ISSUE TITLE
Query regarding loss function

### ISSUE THREAD

**Issue by zaverichintan** [jsyoon0823/TimeGAN#1]
Thank you for providing the source code for the paper. 
I have the following queries: 

1) Which loss function corresponds to the reconstruction loss as in the paper? (I suspect G_loss_S) 
2) The G_loss is not used, where does it correspond in the paper?

**Comment by jsyoon0823** [comment]
Thank you for your interest in our paper.

1. E_loss_T0 (line 212) is the reconstruction loss.
2. G_loss is the summation of G_loss_S, G_loss_U, and G_loss_V
- G_loss_S is the supervised loss (equation 9 in the paper),
- G_loss_U is the unsupervised loss (equation 8 in the paper),
- G_loss_V is the moment matching loss to improve the diversity of the generated samples.

**Comment by zaverichintan** [comment]
G_LOSS  is not used in the code after defining. Any reason why?

**Comment by jsyoon0823** [comment]
G_loss is used in line 220
