### ISSUE TITLE
Simulation Reproducibility

### ISSUE THREAD

**Issue by dreamee-git** [jsyoon0823/TimeGAN#10]
Hi,
I have a trouble about how to reproduce the results on autoregressive multivariate Gaussian data on section 5.1. I write multivariate gaussian data generation code according to your description, but I failed finally. So, What should I do to reproduce it?
Here is my code, can you help me to solve this difficult? Thanks in advance!
```
def normalize(data):
    def min_max_norm(data):
        """ Normalize data to range [0, 1]. """
        min_val = np.min(data, axis=0)
        max_val = np.max(data, axis=0)
        data = (data - min_val)/(max_val - min_val + 1e-7)

        return data
    
    ori_data = np.array(data)

    return min_max_norm(ori_data)

def get_multi_gaussian_data(num_samples, seq_len, num_features, phi, sigma, burn_in=0):
    """ Multivariate Gaussian Data Generation

    Args:
        - num_samples: the number of samples
        - seq_len: sequence length of each time-series sample
        - num_features: the number of features of multivariate gaussian data
        - phi: control the correlation across time steps
        - sigma: control the correlation across features

    Returns:
        - data: generated multi-gaussian data, [num_samples, seq_len, num_features]    
    """
    # First: generate time-series data
    total_len = num_samples + seq_len + burn_in
    x = np.zeros((total_len, num_features))
    ## Set mean and covariace matrix for multivariate normal distribution
    one = np.ones(num_features)
    ide_mat = np.identity(num_features)     # identity matrix
    mu = np.zeros(num_features)
    cov_mat = sigma*one + (1-sigma)*ide_mat
    ## epsilon matrix
    eps_mat = np.random.multivariate_normal(mu, cov_mat, total_len)
    ## generate t+1 step from t step
    x[0, :] = 0     # x_0 = 0
    for t in range(1, total_len):   # x_1, x_2, ..., x_{total_len-1}
        x[t, :] = phi*x[t-1, :] + eps_mat[t-1, :]
    ## delete first burn_in samples
    x = x[burn_in:, :]

    # Second: data normalization
    x = normalize(x)

    # Third: samples generation
    ## Initialize the output
    data = []
    ## each sample has shape seq_len*num_features
    for i in range(x.shape[0] - seq_len):
        data_ = x[i:(i+seq_len), :]
        data.append(data_)
    
    return np.array(data)       # [num_samples, seq_len, num_features]
```

**Comment by jsyoon0823** [comment]
Thank you for your interest in our paper.
Please see the below code for synthetic data generation.

#%% AR Gaussian Multivariate Generation

def AR_Gauss_Generation_X (n, d, t, phi, sigma):

    # Initialization
    Output_X = list()    
    
    mean_val = np.zeros([d,])
    cov_val = np.ones([d,d]) * sigma
    np.fill_diagonal(cov_val, 1)
                    
    # For each sample
    for i in range(n):
        
        Temp_Output_X = np.zeros([t,d])
        
        
        for k in range(t):
              
            # Starting feature
            if (k == 0):            
                Temp_Output_X[k,:] = np.random.multivariate_normal(mean_val, cov_val, 1)
                                
            # AR(1) Generation
            else:                
                Temp_Output_X[k,:] = phi * Temp_Output_X[k-1,:] + (1-phi)*1*np.random.multivariate_normal(mean_val, cov_val, 1)
    
        Output_X.append(Temp_Output_X)    
    
    return Output_X

**Comment by dreamee-git** [comment]
Thank you for your reply.
But what should I do to replicate the performances of Table 1 perfectly. I test on setting $n=3000, t=24, d=3$, but the result not as close as possible to the result reported in Table 1.
Thanks in advance!

**Comment by jsyoon0823** [comment]
I used n=10000, t=24, and d=5.
Hidden dimension = 20, layer = 3, iterations = 50000, batch_size = 128, module = gru.
Thanks!
