### ISSUE TITLE
Error: AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'

### ISSUE THREAD

**Issue by MritulaC** [jsyoon0823/TimeGAN#12]
Hi,
  Thanks  for the wonderful Time Gans approach. I was trying to execute the Juypter notebook from Colab and while executing the line " generated_data = timegan(ori_data, parameters)   " I am getting Attribute Error. Have attached the error detail below. Kindly let me how to overcome this error. Thanks

Mritula

> AttributeError                            Traceback (most recent call last)
<ipython-input-17-80dade3fc85f> in <module>()
      1 # Run TimeGAN
----> 2 generated_data = timegan(ori_data, parameters)
      3 print('Finish Synthetic Data Generation')

/content/cloned-repo/cloned-repo/timegan.py in timegan(ori_data, parameters)
     36   """
     37   # Initialization on the Graph
---> 38   tf.reset_default_graph()
     39 
     40   # Basic Parameters

AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'

**Comment by jsyoon0823** [comment]
Please see the following link: https://stackoverflow.com/questions/40782271/attributeerror-module-tensorflow-has-no-attribute-reset-default-graph

**Comment by MritulaC** [comment]
Hi, Thanks for your response. I did try this, but not helping

**Comment by jsyoon0823** [comment]
This would help for colab.
- https://colab.sandbox.google.com/notebooks/tensorflow_version.ipynb#scrollTo=NeWVBhf1VxlH
- Set it as 1.15.X

**Comment by MritulaC** [comment]
Hi,
 I am still struck in the same place Kindly let me know how to overcome this:
 Thanks
Mritula
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-125-80dade3fc85f> in <module>()
      1 # Run TimeGAN
----> 2 generated_data = timegan(ori_data, parameters)
      3 print('Finish Synthetic Data Generation')

1 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py in placeholder(dtype, shape, name)
   3095   """
   3096   if context.executing_eagerly():
-> 3097     raise RuntimeError("tf.placeholder() is not compatible with "
   3098                        "eager execution.")
   3099 

RuntimeError: tf.placeholder() is not compatible with eager execution.

**Comment by jsyoon0823** [comment]
I think the root cause is tensorflow version.
Please see the below link to solve this issue (https://stackoverflow.com/questions/56561734/runtimeerror-tf-placeholder-is-not-compatible-with-eager-execution).

**Comment by MritulaC** [comment]
Yea, as you said it was all to do with TensorFlow. Finally, it worked, this is what I did:

import tensorflow as tf
tf.compat.v1.disable_eager_execution()

Thanks
