### ISSUE TITLE
question about static features

### ISSUE THREAD

**Issue by Neronjust2017** [jsyoon0823/TimeGAN#13]
Hi, thanks for your great work in time series data generation. However, I have a question that not very clear to me. 
In your paper, you said each time series instance consists of two elements: static features S and temporal features X. And the embedding and recovery functions map these two features to latent vector spaces (using an embedding network for static features and a recurrent embedding network for temporal features). Is that means that the input for embedding network is a tuple contains these two features, and if so how can we get the static fetures? (stastic features are not learned through the training process?). In your code, it seems the raw time series sequences are directly feed to the embedding network and there is only one embedding network. Can you explain for that? Thanks!

**Comment by jsyoon0823** [comment]
Thank you for your interest in our paper.
In our paper, we formalize our problem in general setting that both static and time-series features exist.
However, in the experiment section, we only utilize the time-series features in 4 different datasets. Therefore, our implementation did not include the static data part.
Thanks!
