### ISSUE TITLE
The discriminative score maybe have a error.

### ISSUE THREAD

**Issue by LuJiaWeiwei** [jsyoon0823/TimeGAN#14]
In the TimeGAN/metrics/discriminative_metrics.py file, line 123. Which is 
  y_label_final = np.concatenate((np.ones([len(y_pred_real_curr),]), np.zeros([len(y_pred_real_curr),])), axis = 0)
maybe it is 
  y_label_final = np.concatenate((np.ones([len(y_pred_real_curr),]), np.zeros([len(y_pred_fake_curr),])), axis = 0)
when len(y_pred_fake_curr)==len(y_pred_real_curr). it can work. But when it is not, it maybe wrong.

**Comment by jsyoon0823** [comment]
Great catch! Fixed
