### ISSUE TITLE
Processing the Original Data and the Generated Data

### ISSUE THREAD

**Issue by X404-ch1nVR46** [jsyoon0823/TimeGAN#16]
Hi jsyoon0823,

Thanks for this research and the code, It is great!.

However, I had some doubts about the pre-processing of the original time series data.

In the research, we are assuming the i.i.d. distribution of the input datasets. So, we cut the time-series data (Stock data) and mix it to be i.i.d., and then generate synthetic data for the shorter time-series', but is there a way to get the original as well as the generated times series back like the input format (the format given in the excel sheets for the data)?

**Comment by jsyoon0823** [comment]
Unfortunately, it is not our paper's scope.
The main focus of this paper is to generate the synthetic data if we have multiple iid time-series samples.
So, we first make one time-series to multiple iid time-series samples.
Therefore, reverting the generated samples to the original one time-series is out-of our paper's scope.

Thanks!
