### ISSUE TITLE
problem with real_data_loading function in data_loading.py

### ISSUE THREAD

**Issue by zhixiongtan** [jsyoon0823/TimeGAN#18]
I found the MinMaxScaler operation would be run in timegan function. is there necessary that run MinMaxScaler in real_data_loading funciton?

**Comment by jsyoon0823** [comment]
Good point. It is not necessary to have MinMaxScaler in data loading step. (But it does not mean that MinMaxScaler in data loading function makes errors).
Our timegan function can deal with both normalized and not-normalized inputs.
