### ISSUE TITLE
 AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'

### ISSUE THREAD

**Issue by MritulaC** [jsyoon0823/TimeGAN#19]
Hi,
 When trying to execute the timegan function; I am getting attribute error:
 `# Run TimeGAN
generated_data = timegan(ori_data, parameters)   
print('Finish Synthetic Data Generation')`

> AttributeError                            Traceback (most recent call last)
<ipython-input-12-80dade3fc85f> in <module>()
      1 # Run TimeGAN
----> 2 generated_data = timegan(ori_data, parameters)
      3 print('Finish Synthetic Data Generation')

/content/timeGAN/timegan.py in timegan(ori_data, parameters)
     36   """
     37   # Initialization on the Graph
---> 38   tf.reset_default_graph()
     39 
     40   # Basic Parameters

AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'

HOW TO OVERCOME THIS ERROR?

**Comment by MritulaC** [comment]
!pip install tensorflow==1.14.0

--version downgrade helped

**Comment by Rane90** [comment]
Note that the python version should be 3.6
