### ISSUE TITLE
Which version of Tensorflow is needed to run TimeGAN?

### ISSUE THREAD

**Issue by MritulaC** [jsyoon0823/TimeGAN#20]
Hi,
 Is the TimeGAN implementation is compatible with tensflow version>2?

!pip install tensorflow==1.14.0   

-- version downgrade helped

Mritula

**Comment by MritulaC** [comment]
Kindly confirm

**Comment by jsyoon0823** [comment]
TF: 1.15.0
Keras: 2.3.1
