### ISSUE TITLE
TF is depreciated

### ISSUE THREAD

**Issue by bishlarr** [jsyoon0823/TimeGAN#22]
Hi !

First, thanks for the amazing work.
I would like to use this code but unfortunately, all the warning from your Jupiter Notebook are now errors since TensorFlow dropped the next version.

Is there any way to have the code updated?

Thanks and keep the good job !

**Comment by jsyoon0823** [comment]
Please see the updated codebase. Thanks!

**Comment by Zepp3** [comment]
Hi!

Where do I find the updated codebase. Is it the available codebase in this git, last updated at the 24th April 2020?

**Comment by jsyoon0823** [comment]
Sorry. We have updated the codebase to TF2 in April 2021. However, we
discovered some bugs; thus, we reverted it.

**Comment by Zepp3** [comment]
Ok, I'll just let it run with TF1.15 and python3.7, no problem. Thanks @jsyoon0823!
