### ISSUE TITLE
Autoencoder and latent space

### ISSUE THREAD

**Issue by Salbinus** [jsyoon0823/TimeGAN#23]
Hi,

first - great work!

I'm a bit confused about the role of the autoencoder. According to the paper, the embedder and recovery functions allowing the adversarial network to learn temporal dynamics via lower dimensional representations. When choosing hidden_dim = 24 as in the example, isn't it a higher dimensional representation in latent space?

Thanks and best

**Comment by jsyoon0823** [comment]
Thank you for your interest in our work.
Yes. In some cases (where the original data dimension is small), higher hidden dimensions are helpful to generate more realistic time-series. 
Thanks!
