### ISSUE TITLE
Two theoretical questions

### ISSUE THREAD

**Issue by Sorooshi** [jsyoon0823/TimeGAN#26]
First of all, I'd like to my gratitude for your interesting work, thank you. 

 I have two questions, which I would be happy and thankful if you could answer.
 
Q1: in the paper, at the end of section 3, you claim that Eqn. (1) and Eqn. (2) will take a Jensen-Shannon divergence and Kullback-Leibler divergence, respectively. 

May you please explain why you draw such a conclusion?

Q2: to best my knowledge, during the training time-series models (e.g., a regressor or your timeGAN, etc.). It is recommended not to shuffle the time series. 

However, you shuffle the data points.  May you please clarify why? (Or, If I'm mistaken, please correct me).

**Comment by jsyoon0823** [comment]
Thank you for your interest in our paper.
Please see my answers below.

(A1) JSD and KL divergence
- For JSD, it would be good if you can see the theoretical analyses in this
paper (https://arxiv.org/pdf/1406.2661.pdf).
- For KL, please see this paper (https://arxiv.org/abs/1404.2000)

(A2) We did not shuffle the time-series in the codebase.
- What we did is (i) sample a subset of time-series (without shuffling).
- (ii) we shuffle those sampled time-series. But still the temporal
relationship "within" each sampled time-series is preserved.

Thanks!
