### ISSUE TITLE
Format of output of generated data

### ISSUE THREAD

**Issue by Zepp3** [jsyoon0823/TimeGAN#28]
Hi!

When I generate data, let's say with da dataset with 1000 samples and sequence length 10 and 20 features, the output of the generated data should have the shape (1000, 10, 20), am I right?
How can I convert the data back in the shape of the original data, so (1000, 20)?

**Comment by jsyoon0823** [comment]
Thank you for your interest in our paper.

Unfortunately, I am not sure what your question is.
Why do we need to convert the data from (1000, 10, 20) to (1000, 20)?

Usually 1 time-series sample has X sequence length and Y dimensions; thus,
its shape is (X, Y).
If we have N time-series samples, the shape is (N, X, Y).

It is unclear why you want to convert (N, X, Y) into (N, Y) shape.

Thanks!

**Comment by Zepp3** [comment]
Hi @jsyoon0823 !

Thank you for your answer! I probably posed the question unclear.
In my example, I want to use TimeGAN for synthesizing data of sales and weather conditions.
Let's say I have a dataset with 1000 samples with the features sales (for example how many parts of something where sold that day) and weather conditions (for example the temperature and humidity of that day). Let's say all in all there are 20 features. So I have a dataset with the format (N, Y) with one sample corresponding one day, so (1000, 20).
By using TimeGAN, I have to specify a sequence length, let's say 10 (would have to be optimized by hyperparameter optimization I guess). Therefore I get the output (N, X, Y), so I this example (1000, 10, 20).
But if I want to have the original format of the dataset (N, Y), how can I do that? Do I get in this example one sample of one day by multiplying the sequence length with the sample number, so 1000*10?

**Comment by jsyoon0823** [comment]
Now I get the question.
Unfortunately, it is not possible.
Our main assumption is that all the samples are iid.
Therefore, the temporal relationship across different samples is ignored.

**Comment by chrismark** [comment]
@jsyoon0823 
Does this mean the generated data won't look like the input data (example: stock_data.csv)? 
Is there a way to transform it so it will look like source/stock_data.csv?
Also, is it okay to add a timestamp (seconds from unix epoch) column in the input data? I was thinking it would affect it when it gets normalizing because it will be huge compared to the open,high,etc values but then I noticed volume is there so maybe adding timestamp won't matter?
Thank you.

**Comment by jsyoon0823** [comment]
Yep. We first divide the stock_data.csv into multiple iid samples. 
At that time, we lost the temporal relationship; thus, cannot come back after generating the data. 
Adding the time-stamp can be one solution but we have not tried that option with TimeGAN.
