### ISSUE TITLE
Confused about s(tatic) feature

### ISSUE THREAD

**Issue by asdfqwer2015** [jsyoon0823/TimeGAN#3]
Hi, jsyoon0823:
Your paper looks great and thanks for providing the code for the paper.
En, I'm a little confused about the s(tatic) feature and stationary of input.

For stock case:
- What should **s** mentioned in the paper represents? Can **s** represents average mean or other statistical features and makes **x** <= **x_ori** - mean(**x_ori**) in each window stationary over the long period?

And in your implements:
- Where is **s** and **z_s** terms mentioned in the paper?
- Don't we need to transform original stock data and make it stationary before input to the models?

Did I miss something?
Thanks.

**Comment by asdfqwer2015** [comment]
And
- how to merge batch generated sequences(segmented data)? Simply concatenate may introduce unreasonable temporal dynamics between each adjacent segment pair.

Thanks again.

**Comment by jsyoon0823** [comment]
Thank you for your interest in our paper.

1. Static features
- As you know, static features are defined as the variables whose values do not depend on time. (Time-invariant variables) such as gender, race, etc.
- Unfortunately, in Stock data, there is no static features. 
- Therefore, we do not implement the static feature parts in the paper in this GitHub implementation. 

2. Stationary vs Static
- I think stationary and static is different.
- Random process can be a stationary process but the static mean in the paper is not about the stationary process.

3. Merging
- In the experiments, we assume that all the data comes from iid distribution.
- So, when we cut the time-series data (Stock data) and mixed (permuted), we already treat them as iid.
- Then, the focus of TimeGAN is to generate those sliced time-series and not the original time-series.
- Therefore, there is no way to merge it.
- If you want to generate the original stock data, I think you need to use different preprocessing procedures.

**Comment by asdfqwer2015** [comment]
Thanks for your detailed reply. I'll do stationary transform in preprocessing.
:)
