### ISSUE TITLE
Why flip the data?

### ISSUE THREAD

**Issue by Zepp3** [jsyoon0823/TimeGAN#30]
Hi!

Why does the data get flipped for the purpose of chronology. As far as I can see, the original dataset of energy data for example is already in chronological order.

Kind regards!

**Comment by jsyoon0823** [comment]
For STOCK dataset, its order is inverse chronological.
Thus, we did flipping. 
For ENERGY dataset, you are correct. We do not need flipping.

**Comment by Zepp3** [comment]
Thanks @jsyoon0823

**Comment by jlee118** [comment]
Hi, I'm sorry if this is on a repeated issue, but the stock data in the 'data' folder already seems to be in chronological order.  The first few rows have opening/closing prices in the $50 range, which matches GOOGL's price when it first IPO, the latter rows are all in the $1000s, a plot shows the prices trending upwards over time.  Would you be able to confirm this?

**Comment by jsyoon0823** [comment]
Seems right. No need to flip the data. Will update the code soon. Thank you for catching this.
