### ISSUE TITLE
Saving the Trained TimeGAN model

### ISSUE THREAD

**Issue by Alseides** [jsyoon0823/TimeGAN#32]
First of all thanks a lot for your work. The approach is really interesting.  I'm trying to follow the given example but I have some problems trying to save the model. If i use TimeGAN.save() I got the following error "AttributeError: 'TimeGAN' object has no attribute '__MODEL__' "

I was wondering if I could receive some feedback. Maybe I am doing it wrong.

Thanks for your time.

**Comment by jsyoon0823** [comment]
Thank you for your interest in our paper.

Please see the following closed issue about saving and loading the model.
https://github.com/jsyoon0823/TimeGAN/issues/5

Thanks!
