### ISSUE TITLE
stuck in the first step

### ISSUE THREAD

**Issue by Furyboyy** [jsyoon0823/TimeGAN#36]
I can start the trainning process, but stuck after the first step. What happened?

![image](https://user-images.githubusercontent.com/52880658/139531782-f832e30f-a955-4802-8b74-1ae7dfadd098.png)

**Comment by jsyoon0823** [comment]
Umm... Not sure. Can you increase the number of steps?
Also, can you check with simpler dataset to make sure that this is not a memory issue?
