### ISSUE TITLE
License

### ISSUE THREAD

**Issue by FlorianDe** [jsyoon0823/TimeGAN#37]
Hey Jinsung Yoon,

thanks to you and your colleagues for sharing the code to your amazing Paper _"Time-series Generative Adversarial Networks"_.

I am currently working on my thesis and came across your implementation of the PCA/T-SNE visualization. 
I don't want to use it exactly as it is right now, but wanted to derive my own implementation from your code. However, in order to do this, I wanted to ask about the licensing model for this repository or the code in general.

Could you perhaps include a license file in the repository for clarification?

Thanks in advance,
Florian

**Comment by jsyoon0823** [comment]
Thank you for your interest in our work.

I added the license file in this repository.

Thanks!
