### ISSUE TITLE
no need for g_vars

### ISSUE THREAD

**Issue by zhTnecniv** [jsyoon0823/TimeGAN#38]
On line 221 in timegan.py, we have `GS_solver = tf.train.AdamOptimizer().minimize(G_loss_S, var_list = g_vars + s_vars)`. However `g_vars` are not involved in `G_loss_S` anywhere. Should we delete `g_vars`? Does the author intend to also train the generator in training the supervisor?

**Comment by jsyoon0823** [comment]
You are correct. Other researchers also raised this problem.
I will take that off in the next code update.
Thanks!
