### ISSUE TITLE
How to process the unfixed length samples of the datasets?

### ISSUE THREAD

**Issue by hujb48** [jsyoon0823/TimeGAN#39]
Hi, Yoon! 
     It is a great work for sequence generation! And I am a new at this field, May I ask a question that if I could use my own dataset with different length(timestamp) of each multidimensional sample(in another word,the sample has the shape as [timestamp, features], whose 'timestamp' is unfixed while 'features' is fixed), what should I do to process the data as well as the training model?
Yours, Hu!

**Comment by jsyoon0823** [comment]
Thank you for your interest in our work.
It is quite common that we have different time stamps for each sample.
In that case, we usually apply padding before or after the time-series to match the time stamps across all the samples.
Thanks!

**Comment by hujb48** [comment]
@jsyoon0823 Thanks for your reply, and by the way, have you realized the padding operation? Where could I find it? Thx again!

**Comment by jsyoon0823** [comment]
It is not in this codebase because we use the dataset with same time stamps for all samples.
You can easily find the padding information in Google Search.

**Comment by hujb48** [comment]
@jsyoon0823 ok, it's very kind of you, I would like to try it by myself.
