### ISSUE TITLE
Frequency and Phase of the Sine Function

### ISSUE THREAD

**Issue by sagebei** [jsyoon0823/TimeGAN#40]
In the paper, the parameters of the sine is that frequency falls into the range of (0, 2π), and the phase [−π, π].
xi(t) = sin(2πηt + θ), where η ∼ U[0, 1] and θ ∼ U[−π, π].

However, in the code implementation, the range of both freq and phase is [0, 0.1]. 
freq = np.random.uniform(0, 0.1)            
phase = np.random.uniform(0, 0.1)

Could you please explain the inconsistency? Thank you very much.

**Comment by jsyoon0823** [comment]
Thank you for your interest in our paper.
Unfortunately, during the paper revision, it was not well fixed.
All the results are based on freq and phase range between [0, 0.1].
Sorry for the confusion.

**Comment by sagebei** [comment]
Thank you for your reply!
