### ISSUE TITLE
Results on `Sines` dataset.

### ISSUE THREAD

**Issue by lizhipro** [jsyoon0823/TimeGAN#43]
The `sines` dataset synthesis code is different from the description in the [paper](https://papers.nips.cc/paper/2019/hash/c9efe5f26cd17ba6216bbe2a7d26d490-Abstract.html).

and if I generation the sine wave as mentioned in paper $freq \in U[0,1], phase \in U[-\pi, \pi]$, 

![image](https://user-images.githubusercontent.com/32444071/167304032-e145c1e9-a314-4052-b477-13e4a35f3c91.png)

the predictive scores are completely different, Please does anyone know where the problem is?

> original code:
``` Python
  for k in range(dim):
    # Randomly drawn frequency and phase
    freq = np.random.uniform(0, 0.1)            
    phase = np.random.uniform(0, 0.1)
        
    # Generate sine signal based on the drawn frequency and phase
    temp_data = [np.sin(freq * j + phase) for j in range(seq_len)] 
    temp.append(temp_data)
```

> My code:
``` Python
for k in range(dim):
    # Randomly drawn frequency and phase
    freq = np.random.uniform(0, 1)
    phase = np.random.uniform(-np.pi, np.pi)

    # Generate sine signal based on the drawn frequency and phase
    temp_data = [np.sin(2 * np.pi * freq* j / float(seq_len) + phase) for j in range(seq_len)]
    temp.append(temp_data)
```

**Comment by jsyoon0823** [comment]
Thank you for your question.
There was another person who asked the same question and I answered here (https://github.com/jsyoon0823/TimeGAN/issues/40).
Thanks again!

**Comment by lizhipro** [comment]
> Thank you for your question. There was another person who asked the same question and I answered here (#40). Thanks again!

Thank you for your answer!!!
