### ISSUE TITLE
Why only use a single batch for each iteration?

### ISSUE THREAD

**Issue by gkstkdduq1** [jsyoon0823/TimeGAN#44]
Hi, 

I'm currently working on synthetic stock data generating project. And found TimeGan. Just wonder why the code use only a single mini-batch sampled (128 in example) for each step? not the whole set?

Cheers.

**Comment by jsyoon0823** [comment]
Great point.

There is no specific reason that I use a single batch for each step. 
I can re-implement it as epoch based model but the difference would be marginal.
Instead, I increase the number of iterations (much higher than the usual number of epochs) to make the model convergence.

**Comment by gkstkdduq1** [comment]
Okay, thanks for reply. 

In my case, I want to implement timegan for 1-minute data (about 40,000 samples) I faced data bottleneck because the dataloader only fetching a single batch every iteration. 

Do you think I can train through the whole batches and then, how many iteration would be recommended? 
Currently I increased batch size to 512 for the same reason above

thanks again,
