### ISSUE TITLE
About Univariate Data

### ISSUE THREAD

**Issue by 7unahan** [jsyoon0823/TimeGAN#45]
Hello Sir,

Thank you for impressive works, I try to generate consumption data, and it is really good. 
I have a one issue, I want to train with only one column, but it gives error, how can I do?

Thanks in advance

**Comment by jsyoon0823** [comment]
Thank you for your interest in our paper.

It is not clear where the errors come from. 
However, what I guess is that the input should be 3 dimensional tensor.
For univariate data, you first should make it as (N x T x 1) <- 3d tensor.
Then, put it as the inputs.

Thanks!
