### ISSUE TITLE
Reason for applying MinMax twice

### ISSUE THREAD

**Issue by Soothysay** [jsyoon0823/TimeGAN#46]
Hi,
I've been trying to replicate your model in Pytorch. I had a small question that arose as I was going through your code.
Suppose I loaded the stocks data using `real_data_loading()`. I noticed that the ori_data variable there is [MinMax scaled](https://github.com/jsyoon0823/TimeGAN/blob/b3395cb8f6245c9514223d05c258c572838cf5ab/data_loading.py#L100).
Now, while calling `timegan()` you seem to use [Minmax scaling](https://github.com/jsyoon0823/TimeGAN/blob/b3395cb8f6245c9514223d05c258c572838cf5ab/timegan.py#L66) on the already scaled data.
Am I interpreting wrongly or is this how the code works?
If this is the way, could you tell me why we would need to scale the data twice?

**Comment by jsyoon0823** [comment]
Thank you for your interest in our works!
There is no reason that we put MinMax scaler for both data loading and timegan functions.
We just make timegan function as self-standing function that can handle any data regardless of its normalization.
Thanks!
