### ISSUE TITLE
Output from TimeGAN for time series with data of each day

### ISSUE THREAD

**Issue by Nasrin15** [jsyoon0823/TimeGAN#48]
Hello @jsyoon0823 ,
As the ouput is synthetic time series, as for example I am using time series data from start date to end date. So, how to determine what would be start date and end date of synthetic time series generated?

**Comment by jsyoon0823** [comment]
If you want to generate a single time-series with very long sequence, TimeGAN may not be the solution.
TimeGAN can generate multiple time-series samples. 
Thus, we can identify each generated synthetic sample's start and end dates but not for the multiple time-series samples.

**Comment by Nasrin15** [comment]
Sorry but the answer was not that clear to me.
As you stated 'Thus, we can identify each generated synthetic sample's start and end dates but not for the multiple time-series samples.'
How can we identify start and end date? 
Also as we divide the data into batches of sequence length and then train data with each batch so the output we get is also in the same shape of batches how can we identify start date and end date?

**Comment by jsyoon0823** [comment]
Sorry for the confusion.
What I want to say is that we can identify each sample's time stamp (like time 0 to time T within each sample). 
But we cannot get "date" information that can be consistent across different samples.
So, the conclusion is that we cannot generate the start and end dates that can be consistent across multiple samples.

**Comment by Nasrin15** [comment]
Thanks a lot for replying and clearing doubts.
Okay so for example I had input from start date 01-01 to end date 31-03 the generated time series has samples of 24 sequence length. So if we consider first sample output which has 24 values so what would be t time for first value in 24 sequence length sample? And then when we consider second sample of 24 values from output then what would be time t?

**Comment by jsyoon0823** [comment]
That time t is random. There is no guarantee that time t for the first sequence is always smaller than the time t for the second sequence.
In conclusion, there is no chronological relationships "across" different synthetic sequences.
