### ISSUE TITLE
Saving and loading the GAN

### ISSUE THREAD

**Issue by BowenKwan** [jsyoon0823/TimeGAN#5]
I am trying to save the GAN for the generation of output without training again. However, I am having a problem with saving and loading the TimeGAN. I am trying to save the GAN using Saver.save function. 

On the saving side, 
```
saver = tf.train.Saver()   
sess = tf.Session()
sess.run(tf.global_variables_initializer())

(training)

saver.save(sess, save_path)
```
On the loading side,
```
saver = tf.train.import_meta_graph(meta_path)
sess = tf.Session()
saver.restore(sess, tf.train.latest_checkpoint(checkpoint_path))
```
however, it causes the error of uninitialized value for the generator.

I have tried another way of loading,
```
(define TimeGAN structure)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
saver.restore(sess, tf.train.latest_checkpoint(checkpoint_path))
```
however, the result is very different compared to the one generated after training. I suspected that the generator simply used the initial value, instead of the trained value. 

Am I doing anything wrong and how should I correctly save and load the GAN?

**Comment by jsyoon0823** [comment]
In my case, simple_save works fine.
Please see the following link for more details.
https://www.tensorflow.org/api_docs/python/tf/compat/v1/saved_model/simple_save

**Comment by alejandrofdez-us** [comment]
Dear jsyoon,
could you please provide an example of saving the model? 

I've tried the simple save, but when I load it an exception is raised and says as follows:
```
File "testLoad.py", line 44, in <module>
    graph = load_pb(model_filename)
  File "testLoad.py", line 16, in load_pb
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message with type 'tensorflow.GraphDef'
```

**Comment by jsyoon0823** [comment]
Maybe this link would be helpful (https://cv-tricks.com/tensorflow-tutorial/save-restore-tensorflow-models-quick-complete-tutorial/).

**Comment by AravAct** [comment]
Dear Alejandrodez,
Were you able to load the session, and generate a new sequence, without the training?
How were you able to do it

**Comment by Aravgit** [comment]
Dear Alejandrodez,
Were you able to load the session, and generate a new sequence, without the training?
How were you able to do it?
Thanks
