### ISSUE TITLE
Error in Predictive score?

### ISSUE THREAD

**Issue by AmanKrishna** [jsyoon0823/TimeGAN#51]
Paper:
Therefore, using the synthetic dataset, we train a post-hoc sequence-prediction model (by
optimizing a 2-layer LSTM) to predict next-step temporal vectors over each input sequence. Then,
we evaluate the trained model on the original dataset.

In the File: `predictive_metrics.py`
`X_mb = list(generated_data[i][:-1, :(dim - 1)] for i in train_idx)
T_mb = list(generated_time[i] - 1 for i in train_idx)
Y_mb = list(np.reshape(generated_data[i][1:, (dim - 1)], [len(generated_data[i][1:, (dim - 1)]), 1]) for i in train_idx)`

If I understand correctly: Here the prediction value is the last column of the next row.
Input: generated[i][0][:(dim-1)]
Expected output: generated[i+1][1][dim-1]

Is my understanding correct?

**Comment by jsyoon0823** [comment]
The predictive task is to predict the values of next time point of the last feature.
Our generated_data is a 3 dimensional feature with N x T x D where N is the number of samples, T is the number of sequences and D is the number of dimensions.
We use the same sample's history to predict same sample's future. Thus, the first index should be the same.
We use the previous time stamps to predict futures. Thus, the second index needs one time difference between input and output.
We use the dim-1 features to predict the last feature. Thus, the third index is as you provided.
