### ISSUE TITLE
Discriminative score inconsitence issue

### ISSUE THREAD

**Issue by rriecc** [jsyoon0823/TimeGAN#52]
Hi!

I am trying to reproduce your model and I saw someone tried to convert the code to the tf2 version and you accept the PR, but you revert it back for some reasons. Could I know why you do that?

The visualization metrics for each version (tf1, tf2, PyTorch) are matched. But I have tried the discriminative score code from the commit for tf2 version and I also tried the discriminative score metric in the tf1 version. I even write a Pytorch version discriminative score metric with the same structure as the RNN model. All three models are under the same setting, using the same data as well as well test train splitting method, and running multiple times. 

The order of magnitudes for tf2 and PyTorch are matched. However, in the tf1 version, the score is very low and the order of magnitudes is not at the same level as the other two. Could you provide any explanations?

TF1:
![image](https://user-images.githubusercontent.com/89823566/187825698-085a2809-fc4e-4991-bb52-1bdbf97a8c97.png)
TF2:
![image](https://user-images.githubusercontent.com/89823566/187826666-e3d3b7bd-62d2-4829-a094-711e8d89f477.png)
PyTorch:
![image](https://user-images.githubusercontent.com/89823566/187825813-3fa05235-1234-4751-b2ec-2bc2370c4519.png)

**Comment by jsyoon0823** [comment]
The main reason that we revert the TF2 update is that we saw the significant performance degradation.
I am not sure your TF2 and Pytorch implementations but if the problems are only in the discriminative scores, the problems may be in the discriminator implementation. Please double check that part.

Thanks!

**Comment by rriecc** [comment]
The score in tf2 matched my experiments in PyTorch. Why would the significant performance degradation happen? Do you have any possible explanation? I have double-checked the tf2 code, the only difference is the change depends on the version for discriminative scores.
