### ISSUE TITLE
Hello again! Thank you for your patience. The score in tf2 matched my experiments in PyTorch. Why would the significant performance degradation happen? Do you have any possible explanation? I have double-checked the tf2 code in the past commit, the only difference is the change depends on the version for discriminative scores.

### ISSUE THREAD

**Issue by rriecc** [jsyoon0823/TimeGAN#53]
The score in tf2 matched my experiments in PyTorch. Why would the significant performance degradation happen? Do you have any possible explanation? I have double-checked the tf2 code in the past commit, the only difference is the change depends on the version for discriminative scores.

_Originally posted by @rriecc in https://github.com/jsyoon0823/TimeGAN/issues/52#issuecomment-1238327586_

**Comment by jsyoon0823** [comment]
I am not sure because I have not implemented the TF2 version of TimeGAN.
I also saw the performance degradation. That is the main reason that I revert the TF2 version.
