### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by alejandrofdez-us** [jsyoon0823/TimeGAN#54]
Thanks for sharing your work. 
I installed the packages mentioned in requirements.txt. As it only indicates minimum version I just used pip install package_name.

However, I understand that it won't work with tensorflow version 2, so I had to manually install the last tensorflow 1.x version (currently 1.15). It may be helpful to include these constraints in the requirements.txt

**Comment by jsyoon0823** [comment]
Good idea. Fixed.

**Comment by alejandrofdez-us** [comment]
I was also asked to downgrade protobuf. I used protobuf 3.20.3 and seems to works fine
