### ISSUE TITLE
Non regular time-series

### ISSUE THREAD

**Issue by alejandrofdez-us** [jsyoon0823/TimeGAN#55]
As stated in your paper, you have previously tested TimeGan on "a dataset characterized by discrete values and irregular time stamps."
As in this github package, only regular time stamps datasets are provided, I would like to reproduce the experiment on irregular time stamps datasets. 

¿May the timestamps be present on the dataset and therefore not removed?
¿Which would be the sequence lenght?

Thanks in advance.

**Comment by jsyoon0823** [comment]
You can use the measurement time as additional inputs in the timegan framework.
Then, you can easily generate the irregularly sampled time-series.
