### ISSUE TITLE
Why two scalers?

### ISSUE THREAD

**Issue by alejandrofdez-us** [jsyoon0823/TimeGAN#56]
It seems that data is passed through two min-max scalers. Once at data_loading.py and secondly at timegan.py. Is it correct?

**Comment by jsyoon0823** [comment]
Good catch!
We would like to make our timegan.py as standalone function regardless of data normalization.
Thus, we added min-max scaler within timegan.py.
Note that for min-max scaler, applying the normalization twice does not change the results.

Thanks!
