### ISSUE TITLE
About RCGAN and C-RNN-GAN

### ISSUE THREAD

**Issue by Xing619** [jsyoon0823/TimeGAN#58]
Thanks for your share!
Could you please upload the codes of RCGAN and CRNNGAN?

**Comment by jsyoon0823** [comment]
You can find the links of the RCGAN and CRNNGAN implementation in the supplementary materials of our paper (https://papers.nips.cc/paper/2019/hash/c9efe5f26cd17ba6216bbe2a7d26d490-Abstract.html).
Thanks!
