### ISSUE TITLE
Problem in data normalization

### ISSUE THREAD

**Issue by mijanr** [jsyoon0823/TimeGAN#59]
Hi, 
In tutorial_timegan.ipynb notebook file, in the Data Loading section, "ori_data" is returned from the "real_data_loading" method, which actually returns normalized data, and this ori_data is passed to "timegan" function. 
Inside "timegan", this normalized "ori_data" is normalized again, and later second normalization parameters are used to denormalize the generated data. 
Is it intentional by any chance?
Thank you.

**Comment by jsyoon0823** [comment]
Thank you for your interest in our paper.
Please see this issue (https://github.com/jsyoon0823/TimeGAN/issues/56).
