### ISSUE TITLE
Bidirectional Discriminator

### ISSUE THREAD

**Issue by DamianUS** [jsyoon0823/TimeGAN#60]
Hi @jsyoon0823 ! Great work, the architecture is amazing.

Reading your paper, you stated that "Here we implement d via a bidirectional recurrent network with a feedforward output layer," but I cannot find where the bidirectional RNN (GRU or LSTM) is used within your code.

Does this have a purpose? Does the model work better without the standard RNNs? Maybe I missed where the bidirectionality is added?

Many thanks in advance!

**Comment by jsyoon0823** [comment]
Thank you for your interests.

Yes. We can use Bi-RNN for discriminator.
But we did not see the performance improvements with Bi-RNN in comparison to standard RNN.
Thus, to make the repository as simple as possible, we use standard RNN instead of Bi-RNN.

Thanks!
