### ISSUE TITLE
Sigmoid activation function in recovery (decoder) network

### ISSUE THREAD

**Issue by alejandrofdez-us** [jsyoon0823/TimeGAN#63]
Dear Mr. Yoon,
after inspecting your code (thank you very much for your great work), I have noticed that you use a sigmoid activation function in the recovery network (see next line)
https://github.com/jsyoon0823/TimeGAN/blob/8f6181cb9b9d2fa0c930cd902411d9ac8a308e07/timegan.py#L113 as the final layer of the fully connected layer that translates the latent space to the original feature space. 
This seems weird to me, but I am pretty sure that there should be an explanation. 

Could you please give me some insights about this?

In addition, the model is working great in my use case and datasets after some hyperparameterization search.

Thanks

**Comment by jsyoon0823** [comment]
Thank you for your interest in our work.
As can be seen in this line (https://github.com/jsyoon0823/TimeGAN/blob/master/timegan.py#L303), we renormalize the output of the recovery network to the original feature space.

Also, we use the MinMax normalizer at the beginning of TimeGAN (https://github.com/jsyoon0823/TimeGAN/blob/master/timegan.py#L66). Thus, the output of recovery network should be within [0,1]. Thus, we use sigmoid activation function.

Thanks!
