### ISSUE TITLE
 module 'tensorflow' has no attribute 'reset_default_graph'

### ISSUE THREAD

**Issue by CAssie-FN** [jsyoon0823/TimeGAN#64]
Hi, first of all amazing work but sir, upon running the updated code , i m still facing the error  "module 'tensorflow' has no attribute 'reset_default_graph' " .
Changed code:   module 'tensorflow' has no attribute 'reset_default_graph'
. Please help me resolve this.!
~ thankyou

**Comment by CAssie-FN** [comment]
revised code:   tf.compat.v1.reset_default_graph instead on 'reset_default_graph'

**Comment by jsyoon0823** [comment]
Thanks for resolving yourself!
