### ISSUE TITLE
Several questions regarding architectural choices

### ISSUE THREAD

**Issue by rdvhoorn** [jsyoon0823/TimeGAN#65]
Hi Dr Yoon,

First, thanks for the interesting research and provided source code. I had a couple of questions regarding choices made for the architecture:
1. Do you have any specific reasons for choosing to build TimeGAN on top of the standard GAN architecture rather than a more advanced framework like WGAN-GP? We know that WGAN-GP has both theoretical and empirical benefits over traditional GANs, and you have used it in other works such as ADS-GAN.
2. In the conceptual model, it appears that the generator, embedding, and discriminator all use both the static and temporal features to generate/embed/discriminate the next time step. However, the recovery module only uses the temporal features. Can you explain why this decision was made?
3. In the conceptual model, the discriminator uses both the static and temporal features to discriminate the temporal features, and also separately discriminates the static features. What is the added benefit of this separation? Why would you specifically split up the static and temporal features in this way? Is it to give more emphasis to discriminating the static features, or is there another reason?

**Comment by jsyoon0823** [comment]
Thank you for your interest!

1. There is no specific reason to use standard GAN. We can always replace standard GAN to WGAN-GP in TimeGAN.
2. In this repository, we have not used the static data. All the components are used temporal data only.
3. In the conceptual model (Fig 1(b) in the paper), recovery model also uses static and temporal representations (h_s, h_t).
4. Static and temporal data may have very different characteristics. In that case, we think separately discriminate them would make more sense.

Thanks!
