### ISSUE TITLE
Wrapper function to generate new data?

### ISSUE THREAD

**Issue by Aravgit** [jsyoon0823/TimeGAN#66]
Thank you for sharing this code. I had to convert it to tf v2 to work, currently trying to train my own data.
-----
Question
----------
Is there a wrapper function to generate new data, without training the model again? How / what function do I call to generate synthetic data, without training the model again
I have found issues #5  and #32 , for saving a session, but unable to find any solution to generate new data, for example using something like model.predict()

**Comment by Aravgit** [comment]
Found issues #5 and #32, solutions for the same problem. Thanks

**Comment by jsyoon0823** [comment]
Thanks for your interest in our paper.

If you can save the trained model (here generator), you can also load the generator and do inference later.
In TF1, we use this line to generate new synthetic data after loading the saved model.

generated_data_curr = sess.run(X_hat, feed_dict={Z: Z_mb, X: ori_data, T: ori_time}) 

In TF2, you can use this (https://www.tensorflow.org/tutorials/keras/save_and_load) to do save and load.

Thanks!
