### ISSUE TITLE
version of python 

### ISSUE THREAD

**Issue by AlexRepetti** [jsyoon0823/TimeGAN#71]
Hello I'm sorry but I did not find which version of python you are using for your code? I have different errors in my code and I think it comes from my environment.
Also, is the requirements file still valid?
Thanks in advance

**Comment by jsyoon0823** [comment]
Checked that this code is working with Python version 3.7.4. (But I think it will work with higher versions of Python as well).
Requirements file is valid (please use TF1 as mentioned in requirements file)
