### ISSUE TITLE
About the form of the generated data

### ISSUE THREAD

**Issue by Xing619** [jsyoon0823/TimeGAN#72]
Thanks for your good work and code sharing, but I have a question for you: If I input a time series of 1-11 days, will I generate a time series of 1-11 days? Or do we go back and generate a new number of days 12-22?
Looking forward to your early reply！
Thanks！

**Comment by HaibeiZhu** [comment]
> Thanks for your good work and code sharing, but I have a question for you: If I input a time series of 1-11 days, will I generate a time series of 1-11 days? Or do we go back and generate a new number of days 12-22? Looking forward to your early reply！ Thanks！

I believe we only focus on the length of the time series data. Like the length of your input is 11 days, then the length of the output would be 11 days as well. And you can configure the length based on your need

**Comment by HaibeiZhu** [comment]
Also, I appreciate the authors' effort! This is a great concept!
However, I have another question for the authors. I ran the tutorial notebook with the embedded stock data in a TF1 environment. Other than plotting the "generated_data", I didn't make any changes. However, the generated time series data was quite strange, as shown in the attached figure. I have also tried to slightly modified the hyperparameters for the TimeGAN model. However, the generated time series still looks similar -- it seems the training was broken somehow, or there was something wrong with my configuration. I appreciate your suggestions, thanks

<img width="860" alt="bc6a22c1b18888229a7f2a49929c89a" src="https://user-images.githubusercontent.com/11399578/229973087-bab98e53-bb84-47a0-9774-bce813e73d82.png">

**Comment by jsyoon0823** [comment]
Thanks both.

1. 1-11 days
- Yes. If you put 1-11 days information as the training data, TimeGAN will generate 1-11 days synthetic time-series data.

2. Figure
- For this, can you also show the original time-series data in the plot as well?

**Comment by HaibeiZhu** [comment]
> Thanks both.
> 
> 1. 1-11 days
> 
> * Yes. If you put 1-11 days information as the training data, TimeGAN will generate 1-11 days synthetic time-series data.
> 
> 2. Figure
> 
> * For this, can you also show the original time-series data in the plot as well?

Yes, please check the attached figure for the original time series data.

This data is embedded in this repo and processed by the data pre-processing function. I am not sure if given such training data, the generated data would be so smooth as shown in the previous figure. Also, it seems like if I would have more volatility in the generated time series, I need to set the data segment length to a much larger number, like over 200 or 500 (the segment length in the shown figures is just 25).

![image](https://user-images.githubusercontent.com/11399578/230926212-6f6e2efd-5a78-4a59-a47b-c124ad3e386a.png)

**Comment by HaibeiZhu** [comment]
I have some updated figures. I hope these will help locate the problem. I tried to increase the segment length to 200 to have more volatility in the time series.

And this is the original data
![image](https://user-images.githubusercontent.com/11399578/231328377-14c73e76-1b62-4553-b3cc-fedb2b082631.png)

This is the generated data
![image](https://user-images.githubusercontent.com/11399578/231328446-f2d89a42-e000-492d-b470-ebb21dd6ed0b.png)

I also tried some variations of the model hyper-parameters. However, the results were still the same.
I would appreciate it if you could help with identifying the issue. The code I used was the tutorial in the repo. Thank you!

**Comment by jsyoon0823** [comment]
Thanks for the update. If you use the hyper-parameters used in tutorial, please use the hyper-parameter used in main_timegan.py. Especially, increasing the iteration number matters a lot.
Thanks!
