### ISSUE TITLE
About the discriminator

### ISSUE THREAD

**Issue by luoxia-wen** [jsyoon0823/TimeGAN#73]
Thanks for you and your excellent work! In the other issue you mentioned that the Generator is combination of generator and supervisor. So why not only use G_loss_U to optimize both the parameters of generator and supervisor but use another loss G_loss_U_e to optimize the parameters of generator again?

**Comment by jsyoon0823** [comment]
Understood your question. However, as you know, training GAN framework is unstable.
To make the generator (and supervisor) training more stable, we provide multiple losses that can be better feedback for the generator and supervisor.
