### ISSUE TITLE
A question about evaluating the predictive score

### ISSUE THREAD

**Issue by wmmxk** [jsyoon0823/TimeGAN#74]
First, I really appreciate your work, and kindness answering people's questions. 

The post-hoc RNN trained on synthesized data gets similar performance to a post-hoc RNN trained on the original data. That result itself is very impressive. 
 
I was wondering whether there is a way to use the features learned while training the GAN to get a better predictive performance on the original data, and even on testing data that are not used when training the GAN. One idea in my mind is  what if I start from the trained LSTM for learning the embedding when training a post-hoc RNN for prediction. This idea is kind of like pretraining a model to understand the time series data first, and then fine tuning on a down stream task. 

Could I hear your thoughts on this?

**Comment by jsyoon0823** [comment]
I think your idea seems reasonable in terms of pre-training and self-training frameworks.
If we can get better predictive performance with GAN framework, it would be nice.

Please let me know if you have some reasonable results.
Thanks!
