### ISSUE TITLE
Question about reconstruction of generated sample

### ISSUE THREAD

**Issue by marijn111** [jsyoon0823/TimeGAN#75]
Thanks for the great work and publishing of the codebase!

I have a question about the generated samples that are returned by the model.

I understand that it needs to be renormalised first. 
Since the synthetic sample is in the form of _n_ length, with _seq_ sequences and _dim_ dimensions (similar to the input data after pre-processing), I wonder how this can be transformed again into a sequential time series, just like the original input data. 

Is it a matter of appending all sequences? Or calculating the mean of each sequence and appending those? Or something different?

Any help would be appreciated, thanks!

**Comment by jsyoon0823** [comment]
Thanks for your interest in our paper.

What TimeGAN is doing is generating iid sequences.
Therefore, each sequence (with seq length) is a time-series.
Because those sequences are iid, we cannot connect them into one long time-series.

Thanks!
