### ISSUE TITLE
How to apply 1-dimensional data to the timegan framework

### ISSUE THREAD

**Issue by yxgzhumeng** [jsyoon0823/TimeGAN#76]
How to apply 1-dimensional data to the timegan framework

**Comment by tomo960714** [comment]
Hey!
What kind of data are you using? I had similar problem, so I'm also interested in this question.

**Comment by yxgzhumeng** [comment]
> 
A simple sequential one-dimensional data with only one feature. Have you finished the code？

**Comment by tomo960714** [comment]
I was fortunate enough that I use hypnograms, which made of integers between 1 and 5. So I increased the dimensonality by making a x6 array (5 of the hypnogram values, 1 is padding) and every row is responsible for the corresponding value. So my solution was more on the data side, then the model side.

**Comment by jsyoon0823** [comment]
I think current TimeGAN code can be used for 1 dimensional data. So, the input data size would be (No of samples, No of time points, 1).
