### ISSUE TITLE
Reducing dimensionality with np.mean()

### ISSUE THREAD

**Issue by alejandrofdez-us** [jsyoon0823/TimeGAN#77]
Dear @jsyoon0823 ,
Before computing tsne and pca you are aplying a np.mean over values of timeseries. 

https://github.com/jsyoon0823/TimeGAN/blob/8f6181cb9b9d2fa0c930cd902411d9ac8a308e07/metrics/visualization_metrics.py#L49

I wonder why you decided to do so. 

Wouldn't this approach lead to a loss of correlation between features of ori_data vs generated_data?

Imagine a time series with two features:
feature1 = sin(x)
feature2 = cos(x)

vs a second time series with these two features:
feature1 = cos(x)
feature2 = sin(x)

In this case, wouldn't your implementation lead to believe that both time series are equal?

As always, thank you so much for sharing your research and project.

Regards,
Alejandro.

**Comment by jsyoon0823** [comment]
Thanks for bringing this issue. 
You are correct. If we use mean, we aggregate the information which makes us losing the information.
However, the main reason that I reduce the 3 dimensional data into 2 dimensional data is that PCA and tSNE analyses only works with 2 dimensional data.

Another way would be reshape the 3 dimensional data (NxTxD) into 2 dimensional data (Nx (TD)).

**Comment by alejandrofdez-us** [comment]
Thank you for your response, I will leave here an alternative to do the dimensionality reduction
```python
np.reshape(time_series, (n_samples, n_steps * n_features))
```
