### ISSUE TITLE
Saving Model During Training and Using Generator Independently of Training

### ISSUE THREAD

**Issue by MithunVanniasinghe** [jsyoon0823/TimeGAN#79]
Hello, I am training timeGAN on a GPU in a computing server where I am required to submit batch jobs that have the potential to time out. How can I save the timeGAN model during training and re-load the model to continue training where it left of if training stops in the middle due to time out issues. I have viewed issues #5 and issues #32 but do you have a an example where you save the model. It is not clear from those two issues. 

Also, following training, how can I use the generator independently of training. Since the generator function is nested within timegan() function, how can I used it independently of the training process? 

Thank you in advance for any help.

**Comment by jsyoon0823** [comment]
Thanks for your interest in our paper.

Unfortunately, we do not have some examples for saving the timeGAN model.
But any saving methods working in TF1 can be used. (as explained in the previous issues).
Also, after saving the model, you can always load the model and get the synthetic data by the inference.
