### ISSUE TITLE
Labelled Data

### ISSUE THREAD

**Issue by AnkurDebnath35** [jsyoon0823/TimeGAN#8]
Hi,
I have a doubt about how to implement multiclass labelled data with TimeGAN, as it is clear it takes unlabelled time-series data as input. 
Do I need to train for each class seperately or include the class label as a feature itself?

Thanks in advance.

**Comment by jsyoon0823** [comment]
Yes. TimeGAN is originally designed for unlabeled data as many other generative models are focused on.
I think we can extend TimeGAN for labeled data like how GAN is extended to conditional GAN.
I think there are multiple ways to do this. In addition to what you mentioned above (using labels as features), I think you can also utilize the idea of conditional GAN.
- Using labels as the condition of the generator and discriminator can be another approach for this.
