### ISSUE TITLE
`G_loss_S` does not depend on the generator variables `g_vars`, no need to add it to the solver

### ISSUE THREAD

**Issue by itakatz** [jsyoon0823/TimeGAN#80]
The loss `G_loss_S` does not depend on the generator variables:
https://github.com/jsyoon0823/TimeGAN/blob/8f6181cb9b9d2fa0c930cd902411d9ac8a308e07/timegan.py#L165
https://github.com/jsyoon0823/TimeGAN/blob/8f6181cb9b9d2fa0c930cd902411d9ac8a308e07/timegan.py#L171
https://github.com/jsyoon0823/TimeGAN/blob/8f6181cb9b9d2fa0c930cd902411d9ac8a308e07/timegan.py#L200

so there is no need to include `g_vars` when defining the solver (they will not be updated by the back-propagation):
https://github.com/jsyoon0823/TimeGAN/blob/8f6181cb9b9d2fa0c930cd902411d9ac8a308e07/timegan.py#L221

Note that excluding `g_vars` from the solver does not make any change in output, it just makes the code more clear.

**Comment by jsyoon0823** [comment]
Agreed. Will update the codebase accordingly. Thanks!
