### ISSUE TITLE
timeGAN 1D

### ISSUE THREAD

**Issue by htnhien** [jsyoon0823/TimeGAN#82]
I am doing a project on data 1D with timeGAN , however your code is ues for data with dimension more then 2 . How i can run your code with my data 1D. Thank you

**Comment by Yahya-Abbas** [comment]
I have recently faced a similar issue, I solved it using expand_dims(ori_data, axis=-1)

**Comment by htnhien** [comment]
> I have recently faced a similar issue, I solved it using expand_dims(ori_data, axis=-1)

can I have full code you fix. Thank you
