### ISSUE TITLE
Flipping the data in dataloading.py

### ISSUE THREAD

**Issue by songylleo** [jsyoon0823/TimeGAN#83]
Hi! I have one question about the code 
'# Flip the data to make chronological data 
ori_data = ori_data[::-1]'
 in dataloading.py. 
May I know the reason to apply this flipping step? It seems that the data has already been in the chronological sequence (early on top and later at bottom).
Thanks for any help!

**Comment by jsyoon0823** [comment]
Thanks for your interest.
Original data is saved in the reverse chronological order.
Thus, this is converting that into chronological order.
Thanks!
