### ISSUE TITLE
identify synthetic data

### ISSUE THREAD

**Issue by hanli997** [jsyoon0823/TimeGAN#84]
Thanks for your excellent work.
In question #48 , you mention "we can identify each generated synthetic sample's start and end dates", "we can identify each sample's time stamp (like time 0 to time T within each sample)".
For the generated synthetic data fragments, how do we identify the timestamp of this fragment?(That is, you can correspond the synthetic data to the original data)

**Comment by jsyoon0823** [comment]
Thanks for your interest in our work.

As I mentioned in #48, within each synthetic sample, that sample is chronologically aligned.
However, across different synthetic samples, we cannot identify their order.
So, we cannot correspond the synthetic data to the original data.

Thanks!
