### ISSUE TITLE
Timegan outputs are identical

### ISSUE THREAD

**Issue by 8Jimmy** [jsyoon0823/TimeGAN#86]
When utilizing the tutorial_timegan, I encountered an issue where all the generated data points were identical. Upon investigation, I discovered that despite using different random vectors as input, the outputs of the generators remained the same. The only solution I’ve found is to retrain the model, which is quite time-consuming. I’m seeking assistance on how to address this problem more efficiently. Any guidance would be greatly appreciated!
![图一](https://github.com/jsyoon0823/TimeGAN/assets/97609508/8f58486e-48ec-4c0e-af0c-3bd8c8968e8c)
![图2](https://github.com/jsyoon0823/TimeGAN/assets/97609508/4296c679-405e-45c6-83e3-4d2ed18f663d)

**Comment by Aniket51** [comment]
HI Jimmy.. may be you try using random generator . can you share your code with me to check as I'm getting totally different output.

**Comment by Jimmy3141** [comment]
Thanks! I found that this error always occurs on my computer. However, when I run the code on cloud, it works well. Thanks for your attention.
