### ISSUE TITLE
Poor performance on Energy dataset 

### ISSUE THREAD

**Issue by loredanaiamnitchi** [jsyoon0823/TimeGAN#87]
Hi.
I can't achieve similar results on the Energy dataset as in the paper.
I use the default setting of Stock: main_timegan.py to train on the Energy dataset. 
The result is that: Discriminative Score = 0.4837, Predictive score = 0.3102

I think the parameters in main_timegan.py might not be suitable for the Energy dataset (high dimensional). 
How can I get ideal results on the Energy dataset?

**Comment by PearlBrewer** [comment]
> Hi. I can't achieve similar results on the Energy dataset as in the paper. I use the default setting of Stock: main_timegan.py to train on the Energy dataset. The result is that: Discriminative Score = 0.4837, Predictive score = 0.3102
> 
> I think the parameters in main_timegan.py might not be suitable for the Energy dataset (high dimensional). How can I get ideal results on the Energy dataset?

Hi I was wondering if the problem is solved. Also would you be able to get the similar results on the Stock dataset (using Tensorflow 2)? Thanks.

**Comment by jsyoon0823** [comment]
For each dataset, we need different combinations of hyper-parameters.
And yes, the default setting is for Stock.
Please adjust the hyper-parameters to maximize the performance per each dataset.

Also, currently, our results are only reproducible with our TF1 codebase.
