### ISSUE TITLE
TimeGAN cannot Renormalization properly during data restoration because Min_Max_scaler is used both in data_loading.py and in timegan.py.

### ISSUE THREAD

**Issue by fan0723** [jsyoon0823/TimeGAN#88]
In timeGAN, Min_Max_scaler was applied during data_loading.py, but it was executed again in the "timegan" function. This caused the inability to correctly retrieve the original data's min and max values within timegan, resulting in the inability to properly reconstruct the data in the end.
Removing Min_Max_scaler from data_loading.py allowed the data to be restored correctly afterward.

**Comment by jsyoon0823** [comment]
Agreed with you. 
The main reason that we put normalization for both data-loading and timegan function is to allow users to directly use timegan without relying on data-loading.
But you are correct. If you want to use both data-loading and timegan, you should use normalization once.
