### ISSUE TITLE
Tensorflow 2 version ?

### ISSUE THREAD

**Issue by manu3z** [jsyoon0823/TimeGAN#89]
I have been trying to get my installation of Tensorflow 1 to work with this repo but I have had no luck.
So I migrated the code to TF2 myself, but the results I got on the stock dataset differ from the results shown on the notebook.
My question is: is there a running version of TimeGAN that uses Tensorflow 2? and if not, what would you recommend I do to solve my problem? (where TF1 is not an option)
Thank you.

**Comment by c3llofello** [comment]
Having the same issue myself - is there a TF2 version somewhere? I noticed the repo said revert TF2 upgrade or something to that effect...

**Comment by jsyoon0823** [comment]
Unfortunately, there is no TF2 code for timeGAN. 
We tried before but that failed to reproduce the paper performance.
Thanks!
