### ISSUE TITLE
what is the sequence length of the time-series? is that  the Column length ？

### ISSUE THREAD

**Issue by hearyf** [jsyoon0823/TimeGAN#9]

**Comment by jsyoon0823** [comment]
It is the number of time points for each sample. 
Column length represents the dimensions of the data (feature number).

**Comment by hearyf** [comment]
thank you for your reply.
so the file "energy_data.csv" just has one sample?
Or i got it wrong....

**Comment by jsyoon0823** [comment]
I hope this data description would be helpful for you.
https://archive.ics.uci.edu/ml/datasets/Appliances+energy+prediction

**Comment by Zepp3** [comment]
Hi! I still don't quite understand the thing with the time points. Is it the measurements per sample? For example in one day, the values for the stock dataset got measures 24 times?
