### ISSUE TITLE
The main code runs with no result

### ISSUE THREAD

**Issue by MasterXie-99** [jsyoon0823/TimeGAN#91]
Hello, I would like to ask you about the code running question. I seemed to get stuck in the 【 visualization(ori_data, generated_data,  'pca')】line when I was training the code, the output pca image has only one composite data point, and the subsequent tsne image has no output. I changed the number of training sessions to 5000 for the sake of demonstration. Do you have a solution? Thank you。
![pca](https://github.com/user-attachments/assets/2a232971-a50c-4c8e-99fa-9286b685ed42)
![代码错误](https://github.com/user-attachments/assets/117a8cf3-3216-4ec5-bd4d-c2286f30a792)

**Comment by jsyoon0823** [comment]
Umm.. not sure. When you draw tsne or pca figures, could you use smaller number of samples (i.e., subsampling?).

Also, in order to achieve good results, I recommend to increase the number of training iterations.
